SELECT * FROM customer limit 20

--Q1. What is the total revenue generated by each country?
SELECT "Country", SUM("Quantity" * "Price") AS total_revenue
FROM customer
WHERE "Quantity" > 0
GROUP BY "Country"
ORDER BY total_revenue DESC;

-- Q2. Which customers had at least one returned/cancelled order but
-- still spent more than the average customer overall?

WITH customer_totals AS (
    SELECT "Customer ID", SUM("Quantity" * "Price") AS total_spent
    FROM customer
    WHERE "Customer ID" IS NOT NULL
    GROUP BY "Customer ID"
),
avg_spend AS (
    SELECT AVG(total_spent) AS avg_total FROM customer_totals
),
customers_with_returns AS (
    SELECT DISTINCT "Customer ID"
    FROM customer
    WHERE "Quantity" < 0 AND "Customer ID" IS NOT NULL
)
SELECT ct."Customer ID", ct.total_spent
FROM customer_totals ct
JOIN customers_with_returns cr ON ct."Customer ID" = cr."Customer ID"
CROSS JOIN avg_spend a
WHERE ct.total_spent > a.avg_total
ORDER BY ct.total_spent DESC;


-- Q3. What are the top 5 products by total revenue?

SELECT
    "StockCode",
    "Description",
    SUM("Quantity" * "Price") AS total_revenue
FROM customer
WHERE "Quantity" > 0
GROUP BY "StockCode", "Description"
ORDER BY total_revenue DESC
LIMIT 5;


-- Q4. Compare average order value: UK customers vs. non-UK customers

WITH order_totals AS (
    SELECT
        "Invoice",
        CASE WHEN "Country" = 'United Kingdom' THEN 'UK' ELSE 'Non-UK' END AS market,
        SUM("Quantity" * "Price") AS order_value
    FROM customer
    GROUP BY "Invoice", "Country"
)
SELECT
    market,
    ROUND(AVG(order_value), 2) AS avg_order_value,
    COUNT(*) AS num_orders
FROM order_totals
GROUP BY market;


-- Q5. Do identified (logged-in) customers spend more per order than unidentified (guest/wholesale) transactions?

WITH order_totals AS (
    SELECT
        "Invoice",
        CASE WHEN "Customer ID" IS NULL THEN 'Unidentified' ELSE 'Identified' END AS customer_segment,
        SUM("Quantity" * "Price") AS order_value
    FROM customer
    GROUP BY "Invoice", "Customer ID"
)
SELECT
    customer_segment,
    ROUND(AVG(order_value), 2) AS avg_order_value,
    COUNT(*) AS num_orders
FROM order_totals
GROUP BY customer_segment;

-- Q6. Which 5 products have the highest cancellation rate?
SELECT "StockCode","Description",
    COUNT(*) FILTER (WHERE "Invoice" LIKE 'C%') AS cancelled_count,
    COUNT(*) AS total_count,
    ROUND(100.0 * COUNT(*) FILTER (WHERE "Invoice" LIKE 'C%') / COUNT(*), 2) AS cancellation_rate_pct
FROM customer
GROUP BY "StockCode", "Description"
HAVING COUNT(*) > 20  -- exclude rarely-ordered products so the rate is meaningful
ORDER BY cancellation_rate_pct DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on
-- number of distinct orders placed, and count each segment.
WITH customer_orders AS (
    SELECT "Customer ID", COUNT(DISTINCT "Invoice") AS num_orders
    FROM customer
    WHERE "Customer ID" IS NOT NULL
    GROUP BY "Customer ID"
),
segmented AS (
    SELECT
        "Customer ID",
        num_orders,
        CASE
            WHEN num_orders = 1 THEN 'New'
            WHEN num_orders BETWEEN 2 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_orders
)
SELECT customer_segment, COUNT(*) AS num_customers
FROM segmented
GROUP BY customer_segment
ORDER BY num_customers DESC;

-- Q8. What are the top 3 most purchased products within each country?

WITH product_country_sales AS (
    SELECT
        "Country",
        "StockCode",
        "Description",
        SUM("Quantity") AS total_qty,
        ROW_NUMBER() OVER (PARTITION BY "Country" ORDER BY SUM("Quantity") DESC) AS rn
    FROM customer
    WHERE "Quantity" > 0
      AND "Country" != 'Unknown'
    GROUP BY "Country", "StockCode", "Description"
)
SELECT "Country", "StockCode", "Description", total_qty
FROM product_country_sales
WHERE rn <= 3
ORDER BY "Country", rn;


-- Q9. Are repeat buyers (more than 5 orders) also higher-spending customers on average?

WITH customer_orders AS (
    SELECT
        "Customer ID",
        COUNT(DISTINCT "Invoice") AS num_orders,
        SUM("Quantity" * "Price") AS total_spent
    FROM customer
    WHERE "Customer ID" IS NOT NULL
    GROUP BY "Customer ID"
)
SELECT
    CASE WHEN num_orders > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat Buyer' END AS buyer_type,
    COUNT(*) AS num_customers,
    ROUND(AVG(total_spent), 2) AS avg_total_spent
FROM customer_orders
GROUP BY buyer_type;


-- Q10. What is the revenue contribution of each month (seasonality)?

SELECT
    TO_CHAR(TO_TIMESTAMP("InvoiceDate", 'MM/DD/YYYY HH24:MI'), 'YYYY-MM') AS year_month,
    SUM("Quantity" * "Price") AS total_revenue
FROM customer
WHERE "Quantity" > 0
GROUP BY year_month
ORDER BY year_month;
